/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.CardLayout;
import Model.Customer;
import Model.CustomerDirectory;
import Model.Order;
import Model.OrderDirectory;
import Model.Product;
import Model.ProductDirectory;
import java.time.LocalDateTime;
import javax.swing.JPanel;
/**
 *
 * @author sharathreddy
 */
public class MainJFrame extends javax.swing.JFrame {

    // Master Directories (Data Storage)
    private ProductDirectory productDirectory;
    private CustomerDirectory customerDirectory;
    private OrderDirectory orderDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        // 1. Initialize master directories
        this.productDirectory = new ProductDirectory();
        this.customerDirectory = new CustomerDirectory();
        this.orderDirectory = new OrderDirectory();

        // 2. Populate initial data as required by the assignment
        initializeData();

        // 3. Initialize GUI components generated by NetBeans Form Designer
        initComponents();

        // 4. Set up CardLayout and panels in the WorkArea
        setupWorkArea();

        setTitle("Coffee POS System");
    }

    private void setupWorkArea() {
        CardLayout layout = (CardLayout) WorkArea.getLayout();

        // TEMPORARILY COMMENTED OUT: Uncomment these lines once the respective JPanel files are created.

        // Panel 1: Manage Products
        // ManageProductsJPanel manageProductsPanel = new ManageProductsJPanel(productDirectory);
        // WorkArea.add("ManageProducts", manageProductsPanel);

        // Panel 2: Manage Customers
        // ManageCustomersJPanel manageCustomersPanel = new ManageCustomersJPanel(customerDirectory);
        // WorkArea.add("ManageCustomers", manageCustomersPanel);

        // Panel 3: Manage Orders
        // ManageOrdersJPanel manageOrdersPanel = new ManageOrdersJPanel(orderDirectory, productDirectory, customerDirectory);
        // WorkArea.add("ManageOrders", manageOrdersPanel);

        // Panel 4: Search Customer
        // SearchCustomerJPanel searchCustomerPanel = new SearchCustomerJPanel(customerDirectory);
        // WorkArea.add("SearchCustomer", searchCustomerPanel);

        // Panel 5: Order List
        // OrderListJPanel orderListPanel = new OrderListJPanel(orderDirectory);
        // WorkArea.add("OrderList", orderListPanel);

        // Display a simple placeholder until the first panel is ready
        JPanel defaultPanel = new JPanel();
        defaultPanel.setBackground(new java.awt.Color(204, 255, 255));
        javax.swing.JLabel welcomeLabel = new javax.swing.JLabel("Welcome to the Cafe POS System");
        defaultPanel.add(welcomeLabel);
        WorkArea.add("Default", defaultPanel);
        layout.show(WorkArea, "Default");
    }

    private void initializeData() {
        // --- 1. Products (Minimum 5 required) ---
        Product p1 = productDirectory.addProduct(new Product("101", "Latte", "Coffee", 4.25, 50, 4));
        Product p2 = productDirectory.addProduct(new Product("102", "Cappuccino", "Coffee", 4.75, 45, 5));
        Product p3 = productDirectory.addProduct(new Product("103", "Green Tea", "Tea", 3.25, 100, 2));
        Product p4 = productDirectory.addProduct(new Product("104", "Americano", "Coffee", 3.50, 60, 3));
        Product p5 = productDirectory.addProduct(new Product("105", "Blueberry Muffin", "Pastry", 2.95, 30, 1));

        // --- 2. Customers ---
        Customer c1 = customerDirectory.addCustomer(new Customer("201", "Nitish", "Ahuja", "8573952435"));
        Customer c2 = customerDirectory.addCustomer(new Customer("202", "Jane", "Doe", "6171234567"));
        Customer c3 = customerDirectory.addCustomer(new Customer("203", "John", "Smith", "9789876543"));

        // --- 3. Orders (Minimum 3 required) ---
        orderDirectory.addOrder(new Order("5001", LocalDateTime.now().minusHours(2), "Dine-in", "Card",
                Order.ORDER_STATUSES[3], p1, 2, true, c1));

        orderDirectory.addOrder(new Order("5002", LocalDateTime.now().minusMinutes(30), "Takeout", "Cash",
                Order.ORDER_STATUSES[0], p2, 1, false, c2));

        orderDirectory.addOrder(new Order("5003", LocalDateTime.now(), "Pickup", "Mobile",
                Order.ORDER_STATUSES[1], p3, 3, true, c1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        NavArea = new javax.swing.JPanel();
        btnMngProducts = new javax.swing.JButton();
        btnMngCustomers = new javax.swing.JButton();
        btnMngOrders = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnOrderList = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        WorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavArea.setBackground(new java.awt.Color(255, 255, 255));
        NavArea.setMinimumSize(new java.awt.Dimension(150, 100));
        NavArea.setPreferredSize(new java.awt.Dimension(150, 485));

        btnMngProducts.setText("Manage Products");
        btnMngProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngProductsActionPerformed(evt);
            }
        });

        btnMngCustomers.setText("Manage Customers");
        btnMngCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngCustomersActionPerformed(evt);
            }
        });

        btnMngOrders.setText("Manage Orders");
        btnMngOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOrdersActionPerformed(evt);
            }
        });

        btnSearchCustomer.setText("Search Customer");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        btnOrderList.setText("Order List");
        btnOrderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderListActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblTitle.setText("Cafe ");

        javax.swing.GroupLayout NavAreaLayout = new javax.swing.GroupLayout(NavArea);
        NavArea.setLayout(NavAreaLayout);
        NavAreaLayout.setHorizontalGroup(
            NavAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavAreaLayout.createSequentialGroup()
                .addGroup(NavAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOrderList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavAreaLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblTitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NavAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(NavAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NavAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnMngOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMngCustomers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMngProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        NavAreaLayout.setVerticalGroup(
            NavAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavAreaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitle)
                .addGap(48, 48, 48)
                .addComponent(btnMngProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMngCustomers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMngOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderList)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(NavArea);

        WorkArea.setBackground(new java.awt.Color(255, 255, 255));
        WorkArea.setMinimumSize(new java.awt.Dimension(535, 485));
        WorkArea.setPreferredSize(new java.awt.Dimension(535, 485));
        WorkArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(WorkArea);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOrdersActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.show(WorkArea, "ManageOrders");
    }//GEN-LAST:event_btnMngOrdersActionPerformed

    private void btnMngProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngProductsActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.show(WorkArea, "ManageProducts");
    }//GEN-LAST:event_btnMngProductsActionPerformed

    private void btnMngCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngCustomersActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.show(WorkArea, "ManageCustomers");
    }//GEN-LAST:event_btnMngCustomersActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.show(WorkArea, "SearchCustomer");
    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnOrderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderListActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) WorkArea.getLayout();
        layout.show(WorkArea, "OrderList");
    }//GEN-LAST:event_btnOrderListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Initialize the MainJFrame
                MainJFrame mainFrame = new MainJFrame();
                mainFrame.setVisible(true);
                // Ensure the frame starts centered
                mainFrame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NavArea;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JButton btnMngCustomers;
    private javax.swing.JButton btnMngOrders;
    private javax.swing.JButton btnMngProducts;
    private javax.swing.JButton btnOrderList;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables


}
